using namespace std;
#include <iostream>

int main(){
	1;
	//cout << "Print hrivna: ";
	//int hrivna;
	//cin >> hrivna;
	//cout << "dollar" << hrivna * 0.022 << "\n";
	//cout << "euro" << hrivna * 0.024 << "\n";
	//cout << "bitcoin" << hrivna * 0.0000002815 << "\n";
	2;
	//cout << "Print killometr: ";
	//int killometr;
	//cin >> killometr;
	//cout << "dollar" << killometr * 0.539957 << "\n";
	//cout << "euro" << killometr * 0.621371 << "\n";
	3;
	//cout << "Print a: ";
	//int a;
	//cin >> a;
	//cout << "Print b: ";
	//int b;
	//cin >> b;
	//cout << "a:" << b <<  "\n";
	//cout << "b:" << a <<  "\n";
	4;
	//cout << "Print number: ";
	//string a;
	//cin >> a;
	//cout << "Print number: ";
	//string b;
	//cin >> b;
	//cout << "Print number: ";
	//string c;
	//cin >> c;
	//cout << "Print number: ";
	//string d;
	//cin >> d;
	//cout << "Print number: ";
	//string e;
	//cin >> e;
	//cout << "Print number: ";
	//string f;
	//cin >> f;
	//cout << a + b + c << "your number \n";
	//cout << d + e + f << "your number \n";
	//cout << a + e + c << "Your number with the center inverted \n";
	//cout << d + b + f << "Your number with the center inverted \n";
	5;
	//cout << "Print number:\n";
	//int a;
	//cin >> a;
	//cout << "Print number: \n";
	//int b;
	//cin >> b;
	//cout << "Print number: \n";
	//int c;
	//cin >> c;
	//cout << "Print number: \n";
	//int d;
	//cin >> d;
	//cout << a + b + c + d;
	//cout << a + c << " your number \n";
	//cout << b - d << " your inverted number \n";
	6;
	//cout << "Print number: ";
	//string a;
	//cin >> a;
	//cout << "Print number: ";
	//string b;
	//cin >> b;
	//cout << "Print number: ";
	//string c;
	//cin >> c;
	//cout << a + b + c << " your number \n";
	//cout << a + c << " your number without central digit\n";
	8;
	/*cout << "Print kiligram:\n";
	double poundy;
	cin >> poundy;
	cout << poundy * 0.4059;
	cout << "Print poundy:\n";
	double kiligram;
	cin >> kiligram;
	cout << kiligram * 0.00220462;*/
	9;
	//cout << "Print number: ";
	//string a;
	//cin >> a;
	//cout << "Print number: ";
	//string b;
	//cin >> b;
	//cout << "Print number: ";
	//string c;
	//cin >> c;
	//cout << "Print number: ";
	//cout << a + b + c << "your number \n";
	//cout << c + b + a << "Your number with the center inverted \n";
	}

